namespace LisoScheduleBot.Config;

public enum EnvKeys
{
    BOT_TOKEN,
    WEBHOOK_URL,
    HANGFIRE_PASSWORD,
    HANGFIRE_TIMEZONE,
    CLASSROOMS_JSON,
    GROUPS_JSON,
    LESSON_RECURRENCES_JSON,
    LESSONS_JSON,
    SUBJECTS_JSON,
    TEACHERS_JSON,
    USER_SETTINGS_JSON,
    USERS_JSON
}
